### ISSUE TITLE
Multiple realm with pam_linotp.py plugin ?

### ISSUE THREAD

**Issue by jdelvecchio** [LinOTP/LinOTP#111]
Hi,

Is it possible to authenticate against multiple realms using the pam_linotp.py plugin ?

Here is the content of my file `/etc/pam.d/openvpn` :
```
auth [success=1 default=ignore]  pam_python.so /lib/security/pam_linotp.py realm=flat url=https://linotp.example/validate/simplecheck
auth    requisite                       pam_deny.so
auth    required                        pam_permit.so
account required                        pam_permit.so
```

It seems like it's only possible to use one realm for now.

Regards,
Julien

**Comment by authprivsec** [comment]
Hi,

yes you are correct, you can only define one realm here. 

By default, when no "realm" parameter is defined, LinOTP will search for the given username in the default realm defined in LinOTP. The "realm" parameter in the PAM module allows to define a different realm than the default realm for LinOTP to search the given user name in. It also allows to apply the correct policies for the defined realm in LinOTP. 

If LinOTP does not know the realm to look for the username in (default or specifically defined) a username might be found in more than one realm and it is unclear which user is the correct one. This would lead to unclear authentication conditions and normally should be avoided to avoid security implications.

When no specific realm is defined, a user may enter "username@realm" instead of just the username. LinOTP will then interpret the second part after the @ as the realm. (This might break other PAM modules you might use, tough).

There are possibilities to limit the authentication from specific client IPs to specific realms using LinOTP policies and even override the realm used, depending on the client IPs. Might this help in your use case?

The C based PAM module even allows to further limit the users to a specific UserIDResolver.

Hope I could explain a bit why you can only define one realm in the PAM module.

Best Regards,

Rainer

**Comment by jdelvecchio** [comment]
I understand , thanks a lot for your answer, it has been really helpful
