### ISSUE TITLE
account/dologin gone

### ISSUE THREAD

**Issue by zsoltbarat** [LinOTP/LinOTP#144]
The URL account/dologin for selfservice seems gone in recent versions. Is there a replacement for this functionality?

**Comment by lukengda** [comment]
Take a look at our mfa login documentation: https://www.linotp.org/doc/latest/part-management/policy/selfservice.html

Since 2.10 we have an advanced selfservice login that can be secured with a second factor. I would advise you to inspect a browser to see how login is now done on the selfservice or to read the userservice/login controller code.
