### ISSUE TITLE
Env variables for SSL certs, Enckey and logic for Docker. 

### ISSUE THREAD

**Issue by dyemi511** [LinOTP/LinOTP#157]
I've been using LinOTP and very happy with it, but I'm now migrating to using docker.
Unfortunately the docker LinOTP image constantly overwrites the SSL certs and enckey.

I'm editing and testing to add a couple of extra steps. Either adding 2 new ENV for cert and key for apache2, but also if they exist, not to delete them and create new self signed certs. 

Secondly, since I'm importing an existing DB with tokens and encKey, docker continously overwrites my key, making the DB and linotp unusable.
The secrets file Env is set but still continues to simply over write the key. Another logic not to create a new key if it exists. 
This would then enable this to be used with public certs but also migrating a virtual python environment DB into docker. 

I've have looked at the documentation and have tried all the flags but to no avail. 

On a side note, apache2 is serving up insecure SSL and TLS versions. 
I've adjusted this with a ssl.conf, but this might also be worth an "if defined ENV" to add into the linotp.conf

**Comment by lukengda** [comment]
Please note, that our Dockerfile is only used for CI tests in a conainerized setup. If you create your own Dockerfile, you can adjust the entrypoint to not generate those files. You should be able to mount the files instead of generating new ones on container start. This is just not our focus at the moment as the Dockerfile is not maintained as a production server.
