### ISSUE TITLE
cannot pull Docker image

### ISSUE THREAD

**Issue by theoneandonly-vector** [LinOTP/LinOTP#165]
```
pull access denied for linotp, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by lukengda** [comment]
We do not provide an official Docker image vor LinOTP at the moment. Where or what did you try to pull?

**Comment by theoneandonly-vector** [comment]
I git cloned the repo and just tried:
```
docker-compose up
```
which automatically pulls a few images but not the "linotp"

**Comment by lukengda** [comment]
Okay. You have to build it yourself, we have a view Makefile-Targets that work hand-in-hand with the Debian build process and the Dockerfile. It is used in our CI to build the container. You might need to jump through some hoops that I am currently not aware of, because we do not support Docker as a platform for the open source release at the moment.

If you do have a support subscription, than feel free to contact our support team to discuss your usecase.

It is not ruled out that we will support Docker in the future, but currently it just serves as our internal development and CI infrastructure.
